# -*- coding: utf-8 -*-
"""
公開パックサンプルの訳語辞書（ja名称 → 8言語）。
generate_sample_packs_v2.py から T("ja名称") で参照する。
- キーは日本語名称。値は {en,de,es,fr,it,ko,zh-Hant}（ja はキー自身）。
- 複数ジャンルで再利用する共通アイテムを中心に蓄積し、辞書を育てていく。
- 未登録の語は generate 側で警告を出す（訳し漏れ検出）。

DialSplit の 8 言語訳（UI 共通語）とトーンを揃える方針。
"""

# lang順の値をコンパクトに書くためのヘルパ: en,de,es,fr,it,ko,zh-Hant
def _t(en, de, es, fr, it, ko, zh):
    return {"en": en, "de": de, "es": es, "fr": fr, "it": it, "ko": ko, "zh-Hant": zh}


TERMS = {
    # ===== グループ見出し（絵文字込み） =====
    "💳 貴重品": _t("💳 Valuables", "💳 Wertsachen", "💳 Objetos de valor", "💳 Objets de valeur", "💳 Oggetti di valore", "💳 귀중품", "💳 貴重物品"),
    "🔌 充電まわり": _t("🔌 Charging", "🔌 Laden", "🔌 Carga", "🔌 Recharge", "🔌 Ricarica", "🔌 충전", "🔌 充電"),
    "🧼 洗面・衛生": _t("🧼 Toiletries", "🧼 Toilettenartikel", "🧼 Aseo", "🧼 Trousse de toilette", "🧼 Igiene", "🧼 세면·위생", "🧼 盥洗・衛生"),
    "👕 着替え": _t("👕 Clothes", "👕 Kleidung", "👕 Ropa", "👕 Vêtements", "👕 Vestiti", "👕 옷", "👕 換洗衣物"),
    "👜 あると便利": _t("👜 Nice to have", "👜 Praktisch", "👜 Práctico", "👜 Pratique", "👜 Utile", "👜 있으면 편리", "👜 備而不用"),
    "🛂 渡航書類": _t("🛂 Travel documents", "🛂 Reisedokumente", "🛂 Documentos de viaje", "🛂 Documents de voyage", "🛂 Documenti di viaggio", "🛂 여행 서류", "🛂 出國文件"),
    "🔌 電源・通信": _t("🔌 Power & connectivity", "🔌 Strom & Verbindung", "🔌 Energía y conexión", "🔌 Alimentation et connexion", "🔌 Corrente e connessione", "🔌 전원·통신", "🔌 電源・通訊"),
    "👕 衣類": _t("👕 Clothes", "👕 Kleidung", "👕 Ropa", "👕 Vêtements", "👕 Vestiti", "👕 의류", "👕 衣物"),
    "⛺ 宿泊装備": _t("⛺ Shelter & sleep", "⛺ Übernachtung", "⛺ Pernocta", "⛺ Couchage", "⛺ Pernottamento", "⛺ 숙박 장비", "⛺ 住宿裝備"),
    "🍳 炊事": _t("🍳 Cooking", "🍳 Kochen", "🍳 Cocina", "🍳 Cuisine", "🍳 Cucina", "🍳 취사", "🍳 炊事"),
    "🥾 登山装備": _t("🥾 Hiking gear", "🥾 Wanderausrüstung", "🥾 Equipo de senderismo", "🥾 Matériel de rando", "🥾 Attrezzatura", "🥾 등산 장비", "🥾 登山裝備"),
    "💧 食料・水": _t("💧 Food & water", "💧 Essen & Wasser", "💧 Comida y agua", "💧 Nourriture et eau", "💧 Cibo e acqua", "💧 식량·물", "💧 飲食・水"),
    "⛺ 設営": _t("⛺ Setup", "⛺ Aufbau", "⛺ Montaje", "⛺ Installation", "⛺ Montaggio", "⛺ 설치", "⛺ 搭設"),
    "🛏 快眠": _t("🛏 Sleep", "🛏 Schlafen", "🛏 Descanso", "🛏 Sommeil", "🛏 Riposo", "🛏 숙면", "🛏 睡眠"),
    "🍳 調理": _t("🍳 Cooking", "🍳 Kochen", "🍳 Cocina", "🍳 Cuisine", "🍳 Cucina", "🍳 조리", "🍳 烹調"),
    "🔥 焚き火": _t("🔥 Campfire", "🔥 Lagerfeuer", "🔥 Fogata", "🔥 Feu de camp", "🔥 Falò", "🔥 모닥불", "🔥 營火"),
    "💼 仕事道具": _t("💼 Work items", "💼 Arbeitssachen", "💼 Material de trabajo", "💼 Matériel de travail", "💼 Materiale da lavoro", "💼 업무 도구", "💼 工作用品"),
    "👔 身だしなみ": _t("👔 Grooming", "👔 Pflege", "👔 Aseo personal", "👔 Soins", "👔 Cura personale", "👔 몸단장", "👔 儀容"),
    "🎁 手土産・荷物": _t("🎁 Gifts & extras", "🎁 Gastgeschenke", "🎁 Regalos y extras", "🎁 Cadeaux et extras", "🎁 Regali ed extra", "🎁 선물·짐", "🎁 伴手禮・行李"),
    "🍼 授乳・ミルク": _t("🍼 Feeding", "🍼 Füttern", "🍼 Alimentación", "🍼 Repas de bébé", "🍼 Poppata", "🍼 수유·분유", "🍼 餵奶・奶粉"),
    "🧷 おむつまわり": _t("🧷 Diapering", "🧷 Wickeln", "🧷 Pañales", "🧷 Change", "🧷 Cambio pannolino", "🧷 기저귀", "🧷 尿布"),
    "👶 着替え・ケア": _t("👶 Clothes & care", "👶 Kleidung & Pflege", "👶 Ropa y cuidado", "👶 Vêtements et soins", "👶 Vestiti e cura", "👶 옷·케어", "👶 換洗・照護"),
    "☀️ 暑さ・雨対策": _t("☀️ Sun & rain", "☀️ Sonne & Regen", "☀️ Sol y lluvia", "☀️ Soleil et pluie", "☀️ Sole e pioggia", "☀️ 더위·비 대비", "☀️ 防曬・防雨"),
    "🎒 快適グッズ": _t("🎒 Comfort", "🎒 Komfort", "🎒 Comodidad", "🎒 Confort", "🎒 Comfort", "🎒 편의용품", "🎒 舒適小物"),
    "💧 水・食料": _t("💧 Water & food", "💧 Wasser & Essen", "💧 Agua y comida", "💧 Eau et nourriture", "💧 Acqua e cibo", "💧 물·식량", "💧 水・食物"),
    "🔦 明かり・情報": _t("🔦 Light & info", "🔦 Licht & Info", "🔦 Luz e info", "🔦 Lumière et info", "🔦 Luce e info", "🔦 조명·정보", "🔦 照明・資訊"),
    "🩹 衛生・救急": _t("🩹 Hygiene & first aid", "🩹 Hygiene & Erste Hilfe", "🩹 Higiene y primeros auxilios", "🩹 Hygiène et secours", "🩹 Igiene e pronto soccorso", "🩹 위생·구급", "🩹 衛生・急救"),
    "🧤 防寒・その他": _t("🧤 Warmth & misc", "🧤 Wärme & Sonstiges", "🧤 Abrigo y otros", "🧤 Chaleur et divers", "🧤 Calore e varie", "🧤 방한·기타", "🧤 保暖・其他"),

    # ===== 共通アイテム =====
    "財布・身分証": _t("Wallet & ID", "Geldbörse & Ausweis", "Cartera y DNI", "Portefeuille et pièce d'identité", "Portafoglio e documento", "지갑·신분증", "錢包・證件"),
    "スマホ": _t("Smartphone", "Smartphone", "Móvil", "Smartphone", "Smartphone", "스마트폰", "手機"),
    "鍵": _t("Keys", "Schlüssel", "Llaves", "Clés", "Chiavi", "열쇠", "鑰匙"),
    "現金": _t("Cash", "Bargeld", "Efectivo", "Espèces", "Contanti", "현금", "現金"),
    "モバイルバッテリー": _t("Power bank", "Powerbank", "Batería externa", "Batterie externe", "Power bank", "보조배터리", "行動電源"),
    "充電ケーブル": _t("Charging cable", "Ladekabel", "Cable de carga", "Câble de charge", "Cavo di ricarica", "충전 케이블", "充電線"),
    "充電器": _t("Wall charger", "Ladegerät", "Cargador", "Chargeur secteur", "Caricatore", "충전기", "充電器"),
    "イヤホン": _t("Earphones", "Kopfhörer", "Auriculares", "Écouteurs", "Auricolari", "이어폰", "耳機"),
    "歯ブラシ・歯磨き粉": _t("Toothbrush & paste", "Zahnbürste & -pasta", "Cepillo y pasta de dientes", "Brosse à dents et dentifrice", "Spazzolino e dentifricio", "칫솔·치약", "牙刷・牙膏"),
    "洗顔・スキンケア": _t("Face wash & skincare", "Gesichtsreinigung & Pflege", "Limpieza facial y cuidado", "Nettoyant visage et soins", "Detergente viso e cura", "세안·스킨케어", "洗面・保養"),
    "常備薬": _t("Medicine", "Medikamente", "Medicamentos", "Médicaments", "Medicinali", "상비약", "常備藥"),
    "ハンカチ・ティッシュ": _t("Handkerchief & tissue", "Taschentücher", "Pañuelos", "Mouchoirs", "Fazzoletti", "손수건·휴지", "手帕・面紙"),
    "マスク": _t("Masks", "Masken", "Mascarillas", "Masques", "Mascherine", "마스크", "口罩"),
    "下着": _t("Underwear", "Unterwäsche", "Ropa interior", "Sous-vêtements", "Biancheria intima", "속옷", "內衣褲"),
    "靴下": _t("Socks", "Socken", "Calcetines", "Chaussettes", "Calzini", "양말", "襪子"),
    "Tシャツ": _t("T-shirt", "T-Shirt", "Camiseta", "T-shirt", "Maglietta", "티셔츠", "T恤"),
    "パジャマ": _t("Pajamas", "Schlafanzug", "Pijama", "Pyjama", "Pigiama", "잠옷", "睡衣"),
    "羽織りもの": _t("Light layer", "Überwurf", "Chaqueta ligera", "Veste légère", "Giacca leggera", "겉옷", "外搭"),
    "上着": _t("Jacket", "Jacke", "Chaqueta", "Veste", "Giacca", "겉옷", "外套"),
    "トップス": _t("Tops", "Oberteile", "Tops", "Hauts", "Top", "상의", "上衣"),
    "着替え": _t("Change of clothes", "Wechselkleidung", "Muda de ropa", "Rechange", "Cambio d'abiti", "갈아입을 옷", "換洗衣物"),
    "着替え一式": _t("Change of clothes", "Wechselkleidung", "Muda de ropa", "Vêtements de rechange", "Cambio completo", "갈아입을 옷 한 벌", "整套換洗衣物"),
    "エコバッグ": _t("Reusable bag", "Stoffbeutel", "Bolsa reutilizable", "Sac réutilisable", "Borsa riutilizzabile", "에코백", "環保袋"),
    "折りたたみ傘": _t("Folding umbrella", "Taschenschirm", "Paraguas plegable", "Parapluie pliant", "Ombrello pieghevole", "접이식 우산", "折疊傘"),
    "洗面用具": _t("Toiletries", "Kulturbeutel", "Neceser", "Trousse de toilette", "Kit da toeletta", "세면도구", "盥洗用具"),
    "タオル": _t("Towel", "Handtuch", "Toalla", "Serviette", "Asciugamano", "수건", "毛巾"),
    "水": _t("Water", "Wasser", "Agua", "Eau", "Acqua", "물", "水"),
    "行動食": _t("Trail snacks", "Wandersnacks", "Snacks", "En-cas", "Snack", "행동식", "行動糧"),
    "非常食": _t("Emergency food", "Notproviant", "Comida de emergencia", "Nourriture de secours", "Cibo d'emergenza", "비상식량", "緊急糧食"),
    "地図": _t("Map", "Karte", "Mapa", "Carte", "Cartina", "지도", "地圖"),
    "ヘッドランプ": _t("Headlamp", "Stirnlampe", "Linterna frontal", "Lampe frontale", "Lampada frontale", "헤드램프", "頭燈"),
    "雨具(上下)": _t("Rain gear (top & bottom)", "Regenkleidung", "Chubasquero", "Veste et pantalon de pluie", "Giacca e pantaloni antipioggia", "우비(상하)", "雨衣(上下)"),
    "防寒着": _t("Insulation layer", "Wärmeschicht", "Capa de abrigo", "Couche chaude", "Strato termico", "방한복", "保暖衣物"),
    "パスポート": _t("Passport", "Reisepass", "Pasaporte", "Passeport", "Passaporto", "여권", "護照"),
    "航空券・予約控え": _t("Tickets & bookings", "Tickets & Buchungen", "Billetes y reservas", "Billets et réservations", "Biglietti e prenotazioni", "항공권·예약 확인서", "機票・訂位紀錄"),
    "海外旅行保険証": _t("Travel insurance", "Reiseversicherung", "Seguro de viaje", "Assurance voyage", "Assicurazione viaggio", "해외여행보험증", "海外旅遊保險"),
    "クレジットカード": _t("Credit card", "Kreditkarte", "Tarjeta de crédito", "Carte de crédit", "Carta di credito", "신용카드", "信用卡"),
    "現地通貨": _t("Local cash", "Landeswährung", "Moneda local", "Monnaie locale", "Valuta locale", "현지 통화", "當地貨幣"),
    "変換プラグ": _t("Plug adapter", "Reiseadapter", "Adaptador de enchufe", "Adaptateur de prise", "Adattatore di presa", "변환 플러그", "轉接插頭"),
    "SIM・WiFiルーター": _t("SIM / WiFi router", "SIM / WLAN-Router", "SIM / router WiFi", "SIM / routeur WiFi", "SIM / router WiFi", "SIM·와이파이 라우터", "SIM・WiFi 分享器"),
    "テント": _t("Tent", "Zelt", "Tienda", "Tente", "Tenda", "텐트", "帳篷"),
    "寝袋": _t("Sleeping bag", "Schlafsack", "Saco de dormir", "Sac de couchage", "Sacco a pelo", "침낭", "睡袋"),
    "スリーピングマット": _t("Sleeping mat", "Isomatte", "Esterilla", "Matelas de sol", "Materassino", "매트", "睡墊"),
    "バーナー": _t("Stove", "Kocher", "Hornillo", "Réchaud", "Fornello", "버너", "爐頭"),
    "ガス缶": _t("Gas canister", "Gaskartusche", "Cartucho de gas", "Cartouche de gaz", "Bombola gas", "가스캔", "瓦斯罐"),
    "クッカー": _t("Cookware", "Kochgeschirr", "Utensilios de cocina", "Popote", "Pentolino", "코펠", "炊具"),
    "食器・カトラリー": _t("Dishes & cutlery", "Geschirr & Besteck", "Vajilla y cubiertos", "Vaisselle et couverts", "Stoviglie e posate", "식기·수저", "餐具"),
    "バックパック": _t("Backpack", "Rucksack", "Mochila", "Sac à dos", "Zaino", "배낭", "背包"),
    "デイパック": _t("Daypack", "Tagesrucksack", "Mochila de día", "Sac à dos", "Zaino", "데이백", "登山背包"),
    "トレッキングポール": _t("Trekking poles", "Trekkingstöcke", "Bastones de trekking", "Bâtons de rando", "Bastoncini da trekking", "트레킹 폴", "登山杖"),
    "食料(1泊分)": _t("Food (1 night)", "Essen (1 Nacht)", "Comida (1 noche)", "Nourriture (1 nuit)", "Cibo (1 notte)", "식량(1박분)", "食物(一晚份)"),
    "ノートPC": _t("Laptop", "Laptop", "Portátil", "Ordinateur portable", "Portatile", "노트북", "筆電"),
    "充電器(PC)": _t("Laptop charger", "Laptop-Ladegerät", "Cargador del portátil", "Chargeur d'ordinateur", "Caricatore del portatile", "노트북 충전기", "筆電充電器"),
    "名刺": _t("Business cards", "Visitenkarten", "Tarjetas de visita", "Cartes de visite", "Biglietti da visita", "명함", "名片"),
    "資料・ノート": _t("Documents & notebook", "Unterlagen & Notizbuch", "Documentos y libreta", "Documents et carnet", "Documenti e taccuino", "자료·노트", "資料・筆記本"),
    "ワイシャツ": _t("Dress shirt", "Hemd", "Camisa", "Chemise", "Camicia", "와이셔츠", "襯衫"),
    "整髪料": _t("Hair product", "Haarprodukt", "Producto para el pelo", "Produit coiffant", "Prodotto per capelli", "헤어 제품", "髮膠"),
    "手土産": _t("Gift", "Gastgeschenk", "Regalo", "Cadeau", "Regalo", "선물", "伴手禮"),
    "お薬手帳": _t("Medication record", "Medikamentenpass", "Cartilla de medicación", "Carnet de médicaments", "Libretto farmaci", "약 수첩", "用藥紀錄"),
    "部屋着": _t("Loungewear", "Hausanzug", "Ropa de estar en casa", "Tenue d'intérieur", "Abiti da casa", "실내복", "居家服"),
    # 赤ちゃん連れ
    "哺乳瓶": _t("Baby bottle", "Babyflasche", "Biberón", "Biberon", "Biberon", "젖병", "奶瓶"),
    "粉ミルク": _t("Formula", "Milchpulver", "Leche en polvo", "Lait en poudre", "Latte in polvere", "분유", "配方奶粉"),
    "授乳ケープ": _t("Nursing cover", "Stilltuch", "Cubierta de lactancia", "Cape d'allaitement", "Copertura per allattamento", "수유 가리개", "哺乳巾"),
    "スタイ": _t("Bib", "Lätzchen", "Babero", "Bavoir", "Bavaglino", "턱받이", "圍兜"),
    "紙おむつ": _t("Diapers", "Windeln", "Pañales", "Couches", "Pannolini", "기저귀", "紙尿布"),
    "おしりふき": _t("Baby wipes", "Feuchttücher", "Toallitas", "Lingettes", "Salviette", "물티슈", "濕紙巾"),
    "おむつ替えシート": _t("Changing pad", "Wickelunterlage", "Cambiador", "Tapis à langer", "Fasciatoio", "기저귀 교환 매트", "尿布墊"),
    "防臭袋": _t("Odor-proof bags", "Geruchsdichte Beutel", "Bolsas antiolor", "Sacs anti-odeurs", "Sacchetti antiodore", "방취 봉투", "防臭袋"),
    "ベビー服": _t("Baby clothes", "Babykleidung", "Ropa de bebé", "Vêtements de bébé", "Abiti per neonato", "아기 옷", "嬰兒服"),
    "ガーゼ": _t("Gauze cloth", "Mulltuch", "Gasa", "Lange", "Garza", "거즈", "紗布巾"),
    "母子手帳・保険証": _t("Health records & card", "Vorsorgeheft & Karte", "Cartilla y tarjeta sanitaria", "Carnet de santé et carte", "Libretto sanitario e tessera", "모자수첩·보험증", "母子手冊・健保卡"),
    "ベビー用保湿": _t("Baby lotion", "Babylotion", "Loción de bebé", "Lait pour bébé", "Crema per neonati", "아기 로션", "嬰兒保濕乳"),
    # フェス
    "レインポンチョ": _t("Rain poncho", "Regenponcho", "Poncho de lluvia", "Poncho de pluie", "Poncho antipioggia", "우비 판초", "雨衣斗篷"),
    "帽子": _t("Hat", "Hut", "Gorro", "Chapeau", "Cappello", "모자", "帽子"),
    "日焼け止め": _t("Sunscreen", "Sonnencreme", "Protector solar", "Crème solaire", "Crema solare", "선크림", "防曬乳"),
    "レジャーシート": _t("Ground sheet", "Picknickdecke", "Manta de pícnic", "Tapis de sol", "Telo da picnic", "돗자리", "野餐墊"),
    "折りたたみ椅子": _t("Folding chair", "Klappstuhl", "Silla plegable", "Chaise pliante", "Sedia pieghevole", "접이식 의자", "折疊椅"),
    "飲み物": _t("Drinks", "Getränke", "Bebidas", "Boissons", "Bevande", "음료", "飲料"),
    "ウェットティッシュ": _t("Wet wipes", "Feuchttücher", "Toallitas húmedas", "Lingettes", "Salviette umide", "물티슈", "濕紙巾"),
    # 防災
    "保存水(500ml)": _t("Bottled water (500ml)", "Wasserflasche (500 ml)", "Agua embotellada (500 ml)", "Eau en bouteille (500 ml)", "Acqua in bottiglia (500 ml)", "보존수(500ml)", "保存水(500ml)"),
    "携帯トイレ": _t("Portable toilet", "Notfalltoilette", "Inodoro portátil", "Toilettes portables", "Toilette portatile", "휴대용 화장실", "行動廁所"),
    "懐中電灯": _t("Flashlight", "Taschenlampe", "Linterna", "Lampe torche", "Torcia", "손전등", "手電筒"),
    "携帯ラジオ": _t("Portable radio", "Radio", "Radio portátil", "Radio portable", "Radio portatile", "휴대용 라디오", "手提收音機"),
    "乾電池": _t("Batteries", "Batterien", "Pilas", "Piles", "Batterie", "건전지", "乾電池"),
    "救急セット": _t("First-aid kit", "Erste-Hilfe-Set", "Botiquín", "Trousse de secours", "Kit di primo soccorso", "구급세트", "急救包"),
    "アルミブランケット": _t("Emergency blanket", "Rettungsdecke", "Manta térmica", "Couverture de survie", "Coperta termica", "은박 담요", "鋁箔保暖毯"),
    "軍手": _t("Work gloves", "Arbeitshandschuhe", "Guantes de trabajo", "Gants de travail", "Guanti da lavoro", "면장갑", "工作手套"),
    "現金(小銭含む)": _t("Cash (incl. coins)", "Bargeld (inkl. Münzen)", "Efectivo (con monedas)", "Espèces (avec pièces)", "Contanti (con monete)", "현금(동전 포함)", "現金(含零錢)"),
    "身分証コピー": _t("Copy of ID", "Ausweiskopie", "Copia del DNI", "Copie de la pièce d'identité", "Copia del documento", "신분증 사본", "證件影本"),

    # ===== 第1カテゴリ（旅行・実用）パック名・追加アイテム =====
    "国内旅行 1泊2日": _t("Overnight Trip", "Kurztrip (1 Nacht)", "Escapada de una noche", "Escapade d'une nuit", "Gita di una notte", "1박 2일 여행", "國內旅行 兩天一夜"),
    "国内旅行 2泊3日": _t("Three-Day Trip", "Kurzreise (2 Nächte)", "Viaje de tres días", "Voyage de trois jours", "Viaggio di tre giorni", "2박 3일 여행", "國內旅行 三天兩夜"),
    "海外旅行": _t("Overseas Trip", "Auslandsreise", "Viaje al extranjero", "Voyage à l'étranger", "Viaggio all'estero", "해외여행", "海外旅行"),
    "日帰り登山": _t("Day Hike", "Tageswanderung", "Excursión de un día", "Randonnée à la journée", "Escursione giornaliera", "당일 등산", "一日登山"),
    "テント泊登山": _t("Overnight Backpacking", "Trekking mit Übernachtung", "Trekking con pernocta", "Trek avec bivouac", "Trekking con pernottamento", "박영 등산", "紮營登山"),
    "ファミリーキャンプ": _t("Family Camping", "Familiencamping", "Camping en familia", "Camping en famille", "Campeggio in famiglia", "가족 캠핑", "家庭露營"),
    "出張（ビジネス）": _t("Business Trip", "Geschäftsreise", "Viaje de negocios", "Voyage d'affaires", "Viaggio di lavoro", "출장(비즈니스)", "商務出差"),
    "赤ちゃん連れ旅行": _t("Trip with a Baby", "Reise mit Baby", "Viaje con bebé", "Voyage avec bébé", "Viaggio con neonato", "아기 동반 여행", "帶嬰兒旅行"),
    "フェス・野外イベント": _t("Festival / Outdoor Event", "Festival / Open-Air", "Festival / evento al aire libre", "Festival / événement en plein air", "Festival / evento all'aperto", "페스티벌·야외 행사", "音樂節・戶外活動"),
    "防災リュック": _t("Emergency Kit", "Notfallrucksack", "Kit de emergencia", "Kit d'urgence", "Kit di emergenza", "재난 대비 가방", "防災背包"),
    "💳 必須品": _t("💳 Essentials", "💳 Grundausstattung", "💳 Imprescindibles", "💳 Indispensables", "💳 Essenziali", "💳 필수품", "💳 必需品"),
    "コンパス": _t("Compass", "Kompass", "Brújula", "Boussole", "Bussola", "나침반", "指南針"),
    "タープ": _t("Tarp", "Tarp", "Toldo", "Bâche", "Telo", "타프", "天幕"),
    "ペグ・ハンマー": _t("Pegs & hammer", "Heringe & Hammer", "Estacas y martillo", "Sardines et marteau", "Picchetti e martello", "팩·망치", "營釘・槌子"),
    "グランドシート": _t("Ground sheet", "Bodenplane", "Lona de suelo", "Tapis de sol", "Telo pavimento", "그라운드 시트", "地布"),
    "マット": _t("Sleeping pad", "Isomatte", "Esterilla", "Matelas", "Materassino", "매트", "睡墊"),
    "ランタン": _t("Lantern", "Laterne", "Farol", "Lanterne", "Lanterna", "랜턴", "營燈"),
    "ツーバーナー": _t("Two-burner stove", "Zwei-Flammen-Kocher", "Hornillo de dos fuegos", "Réchaud deux feux", "Fornello a due fuochi", "투 버너", "雙口爐"),
    "クーラーボックス": _t("Cooler box", "Kühlbox", "Nevera portátil", "Glacière", "Frigo portatile", "아이스박스", "保冷箱"),
    "調理器具一式": _t("Cookware set", "Kochset", "Juego de cocina", "Kit de cuisine", "Set da cucina", "조리기구 세트", "炊具組"),
    "食器類": _t("Tableware", "Geschirr", "Vajilla", "Vaisselle", "Stoviglie", "식기류", "餐具"),
    "焚き火台": _t("Fire pit", "Feuerschale", "Fogón portátil", "Brasero", "Braciere", "화로대", "火盆架"),
    "薪・着火剤": _t("Firewood & starter", "Feuerholz & Anzünder", "Leña y pastillas", "Bois et allume-feu", "Legna e accendifuoco", "장작·착화제", "柴薪・助燃劑"),
    "軍手・トング": _t("Gloves & tongs", "Handschuhe & Zange", "Guantes y pinzas", "Gants et pince", "Guanti e pinze", "장갑·집게", "手套・夾子"),
    "下着・靴下": _t("Underwear & socks", "Unterwäsche & Socken", "Ropa interior y calcetines", "Sous-vêtements et chaussettes", "Intimo e calzini", "속옷·양말", "內衣褲・襪子"),

    # ===== 第1カテゴリ memo（説明文）=====
    "__memo__trip_domestic_1n2d": _t("For a weekend getaway. Clothes, toiletries, and charging basics.", "Für einen Wochenendausflug. Kleidung, Toilettenartikel und Ladegeräte.", "Para una escapada de fin de semana. Ropa, aseo y carga.", "Pour un week-end. Vêtements, toilette et recharge.", "Per una gita nel weekend. Vestiti, igiene e ricarica.", "주말 나들이에. 옷·세면·충전 기본 세트.", "適合週末出遊。換洗、盥洗、充電的基本組合。"),
    "__memo__trip_domestic_2n3d": _t("For a slightly longer trip. Extra changes of clothes.", "Für eine etwas längere Reise. Zusätzliche Wechselkleidung.", "Para un viaje algo más largo. Ropa de cambio adicional.", "Pour un séjour un peu plus long. Des vêtements de rechange en plus.", "Per un viaggio un po' più lungo. Cambi d'abito extra.", "조금 긴 여행에. 갈아입을 옷을 넉넉히.", "適合稍長的旅行。多帶幾套換洗衣物。"),
    "__memo__trip_overseas": _t("Passport, adapters, and other overseas essentials.", "Reisepass, Adapter und weitere Auslands-Essentials.", "Pasaporte, adaptadores y otros básicos para el extranjero.", "Passeport, adaptateurs et autres essentiels à l'étranger.", "Passaporto, adattatori e altri essenziali per l'estero.", "여권, 변환 플러그 등 해외 필수품.", "護照、轉接頭等海外必備物品。"),
    "__memo__hike_day": _t("Carry 2L water, snacks, and rain gear. For day hikes.", "2 L Wasser, Snacks und Regenkleidung mitnehmen. Für Tagestouren.", "Lleva 2 L de agua, comida y chubasquero. Para excursiones de un día.", "Emportez 2 L d'eau, en-cas et veste de pluie. Pour la journée.", "Porta 2 L d'acqua, snack e giacca antipioggia. Per la giornata.", "물 2L·행동식·우비 지참. 당일 산행용.", "帶2L水、行動糧與雨具。適合一日登山。"),
    "__memo__hike_tent": _t("Tent, sleeping bag, and cooking gear. Weight matters.", "Zelt, Schlafsack und Kochausrüstung. Auf das Gewicht achten.", "Tienda, saco de dormir y equipo de cocina. El peso importa.", "Tente, sac de couchage et matériel de cuisine. Le poids compte.", "Tenda, sacco a pelo e attrezzatura da cucina. Il peso conta.", "텐트·침낭·취사도구. 무게 관리가 중요.", "帳篷、睡袋、炊具。重量很重要。"),
    "__memo__camp_family": _t("Tent, cooking, and campfire gear for car camping.", "Zelt, Küche und Lagerfeuer-Ausrüstung fürs Autocamping.", "Tienda, cocina y fogata para camping con coche.", "Tente, cuisine et feu de camp pour le camping en voiture.", "Tenda, cucina e falò per il campeggio in auto.", "오토캠핑용 텐트·조리·모닥불 장비.", "汽車露營用的帳篷、炊事與營火裝備。"),
    "__memo__business_trip": _t("Laptop, business cards, chargers. Minimal for one night.", "Laptop, Visitenkarten, Ladegeräte. Minimal für eine Nacht.", "Portátil, tarjetas, cargadores. Mínimo para una noche.", "Ordinateur, cartes de visite, chargeurs. Minimal pour une nuit.", "Portatile, biglietti da visita, caricatori. Minimo per una notte.", "노트북·명함·충전기. 1박 미니멀 구성.", "筆電、名片、充電器。一晚精簡構成。"),
    "__memo__trip_with_baby": _t("Bring extra diapers, milk, and clothes. Don't forget records.", "Extra Windeln, Milch und Kleidung. Vorsorgeheft nicht vergessen.", "Lleva pañales, leche y ropa de más. No olvides la cartilla.", "Prévoyez couches, lait et vêtements en plus. N'oubliez pas le carnet.", "Porta pannolini, latte e vestiti extra. Non dimenticare il libretto.", "기저귀·분유·옷을 넉넉히. 수첩도 잊지 마세요.", "多帶尿布、奶粉與衣物。別忘了手冊。"),
    "__memo__festival": _t("Sun, rain, and hydration ready. Pack light and mobile.", "Für Sonne, Regen und Flüssigkeit gerüstet. Leicht und mobil packen.", "Listo para sol, lluvia e hidratación. Equipaje ligero y práctico.", "Prêt pour le soleil, la pluie et l'hydratation. Léger et mobile.", "Pronto per sole, pioggia e idratazione. Leggero e pratico.", "햇볕·비·수분 보충 대비. 가볍게 준비.", "防曬、防雨、補水齊全。輕便好行動。"),
    "__memo__emergency_kit": _t("Grab-and-go kit. Review contents and expiry dates regularly.", "Notfallset zum Mitnehmen. Inhalt und Haltbarkeit regelmäßig prüfen.", "Kit para llevar. Revisa contenido y caducidad con regularidad.", "Kit prêt à emporter. Vérifiez contenu et péremption régulièrement.", "Kit pronto all'uso. Controlla contenuto e scadenze regolarmente.", "비상 반출 가방. 내용물과 유통기한을 정기 점검.", "緊急避難包。定期檢查內容物與有效期限。"),

    # ===== 第2カテゴリ（スポーツ）パック名・グループ =====
    "ジム・筋トレ": _t("Gym Workout", "Fitnessstudio", "Gimnasio", "Salle de sport", "Palestra", "헬스·근력운동", "健身・重訓"),
    "ランニング": _t("Running", "Laufen", "Running", "Course à pied", "Corsa", "러닝", "跑步"),
    "ゴルフ": _t("Golf", "Golf", "Golf", "Golf", "Golf", "골프", "高爾夫"),
    "テニス": _t("Tennis", "Tennis", "Tenis", "Tennis", "Tennis", "테니스", "網球"),
    "スキー・スノボ": _t("Ski & Snowboard", "Ski & Snowboard", "Esquí y snowboard", "Ski et snowboard", "Sci e snowboard", "스키·스노보드", "滑雪・單板"),
    "ボルダリング": _t("Bouldering", "Bouldern", "Búlder", "Escalade de bloc", "Bouldering", "볼더링", "抱石"),
    "サッカー・フットサル": _t("Soccer / Futsal", "Fußball / Futsal", "Fútbol / futsal", "Foot / futsal", "Calcio / futsal", "축구·풋살", "足球・五人制"),
    "ヨガ": _t("Yoga", "Yoga", "Yoga", "Yoga", "Yoga", "요가", "瑜伽"),
    "👟 トレーニング": _t("👟 Training", "👟 Training", "👟 Entrenamiento", "👟 Entraînement", "👟 Allenamento", "👟 트레이닝", "👟 訓練"),
    "🥤 補給・ケア": _t("🥤 Fuel & care", "🥤 Verpflegung & Pflege", "🥤 Nutrición y cuidado", "🥤 Ravitaillement et soins", "🥤 Nutrizione e cura", "🥤 보충·케어", "🥤 補給・保養"),
    "🏃 装備": _t("🏃 Gear", "🏃 Ausrüstung", "🏃 Equipo", "🏃 Équipement", "🏃 Attrezzatura", "🏃 장비", "🏃 裝備"),
    "📱 サポート": _t("📱 Support", "📱 Unterstützung", "📱 Apoyo", "📱 Support", "📱 Supporto", "📱 서포트", "📱 輔助"),
    "⛳ プレー用品": _t("⛳ Play items", "⛳ Spielutensilien", "⛳ Material de juego", "⛳ Matériel de jeu", "⛳ Materiale da gioco", "⛳ 플레이 용품", "⛳ 比賽用品"),
    "👕 ウェア": _t("👕 Apparel", "👕 Bekleidung", "👕 Ropa", "👕 Tenue", "👕 Abbigliamento", "👕 웨어", "👕 服裝"),
    "☀️ 対策・その他": _t("☀️ Protection & misc", "☀️ Schutz & Sonstiges", "☀️ Protección y otros", "☀️ Protection et divers", "☀️ Protezione e varie", "☀️ 대비·기타", "☀️ 防護・其他"),
    "🎾 用具": _t("🎾 Equipment", "🎾 Ausrüstung", "🎾 Equipo", "🎾 Équipement", "🎾 Attrezzatura", "🎾 용구", "🎾 用具"),
    "👕 ウェア・ケア": _t("👕 Wear & care", "👕 Bekleidung & Pflege", "👕 Ropa y cuidado", "👕 Tenue et soins", "👕 Abbigliamento e cura", "👕 웨어·케어", "👕 服裝・保養"),
    "🎿 ウェア": _t("🎿 Outerwear", "🎿 Oberbekleidung", "🎿 Ropa de abrigo", "🎿 Vêtements", "🎿 Capispalla", "🎿 웨어", "🎿 外著"),
    "🥽 小物": _t("🥽 Accessories", "🥽 Zubehör", "🥽 Accesorios", "🥽 Accessoires", "🥽 Accessori", "🥽 소품", "🥽 小配件"),
    "🧴 ケア・その他": _t("🧴 Care & misc", "🧴 Pflege & Sonstiges", "🧴 Cuidado y otros", "🧴 Soins et divers", "🧴 Cura e varie", "🧴 케어·기타", "🧴 保養・其他"),
    "🧗 クライミング": _t("🧗 Climbing", "🧗 Klettern", "🧗 Escalada", "🧗 Escalade", "🧗 Arrampicata", "🧗 클라이밍", "🧗 攀岩"),
    "👕 その他": _t("👕 Misc", "👕 Sonstiges", "👕 Otros", "👕 Divers", "👕 Varie", "👕 기타", "👕 其他"),
    "⚽ 装備": _t("⚽ Gear", "⚽ Ausrüstung", "⚽ Equipo", "⚽ Équipement", "⚽ Attrezzatura", "⚽ 장비", "⚽ 裝備"),
    "🥤 サポート": _t("🥤 Support", "🥤 Unterstützung", "🥤 Apoyo", "🥤 Support", "🥤 Supporto", "🥤 서포트", "🥤 輔助"),
    "🧘 ヨガ用品": _t("🧘 Yoga items", "🧘 Yoga-Zubehör", "🧘 Material de yoga", "🧘 Matériel de yoga", "🧘 Attrezzatura yoga", "🧘 요가 용품", "🧘 瑜伽用品"),
    "🥤 その他": _t("🥤 Misc", "🥤 Sonstiges", "🥤 Otros", "🥤 Divers", "🥤 Varie", "🥤 기타", "🥤 其他"),
    # スポーツ アイテム
    "トレーニングウェア": _t("Workout clothes", "Trainingskleidung", "Ropa de entreno", "Tenue de sport", "Abbigliamento sportivo", "운동복", "運動服"),
    "シューズ": _t("Training shoes", "Sportschuhe", "Zapatillas", "Chaussures", "Scarpe", "운동화", "運動鞋"),
    "グローブ": _t("Gloves", "Handschuhe", "Guantes", "Gants", "Guanti", "장갑", "手套"),
    "プロテイン": _t("Protein", "Protein", "Proteína", "Protéines", "Proteine", "프로틴", "乳清蛋白"),
    "シェイカー": _t("Shaker bottle", "Shaker", "Shaker", "Shaker", "Shaker", "셰이커", "搖搖杯"),
    "シャンプー・ボディソープ": _t("Shampoo & body wash", "Shampoo & Duschgel", "Champú y gel", "Shampoing et gel douche", "Shampoo e bagnoschiuma", "샴푸·바디워시", "洗髮精・沐浴乳"),
    "ランニングシューズ": _t("Running shoes", "Laufschuhe", "Zapatillas de running", "Chaussures de course", "Scarpe da corsa", "러닝화", "跑鞋"),
    "ウェア(上下)": _t("Outfit", "Sportkleidung", "Conjunto deportivo", "Tenue", "Completo", "웨어(상하)", "上下運動服"),
    "ランニングソックス": _t("Running socks", "Laufsocken", "Calcetines de running", "Chaussettes de course", "Calzini da corsa", "러닝 양말", "跑步襪"),
    "キャップ": _t("Cap", "Kappe", "Gorra", "Casquette", "Cappellino", "캡", "帽子"),
    "ランニングウォッチ": _t("Running watch", "Laufuhr", "Reloj de running", "Montre de course", "Orologio da corsa", "러닝 워치", "跑錶"),
    "ジェル・補給食": _t("Energy gel", "Energie-Gel", "Gel energético", "Gel énergétique", "Gel energetico", "에너지 젤", "能量膠"),
    "反射材・ライト": _t("Reflector & light", "Reflektor & Licht", "Reflectante y luz", "Réflecteur et lampe", "Riflettente e luce", "반사재·라이트", "反光片・燈"),
    "ゴルフグローブ": _t("Golf glove", "Golfhandschuh", "Guante de golf", "Gant de golf", "Guanto da golf", "골프 장갑", "高爾夫手套"),
    "ボール": _t("Ball", "Ball", "Pelota", "Balle", "Palla", "볼", "球"),
    "ティー": _t("Tees", "Tees", "Tees", "Tees", "Tee", "티", "球釘"),
    "マーカー": _t("Ball marker", "Ballmarker", "Marcador", "Marqueur", "Segnapalla", "마커", "球位記號"),
    "ゴルフウェア": _t("Golf wear", "Golfbekleidung", "Ropa de golf", "Tenue de golf", "Abbigliamento golf", "골프 웨어", "高爾夫球衣"),
    "ゴルフシューズ": _t("Golf shoes", "Golfschuhe", "Zapatos de golf", "Chaussures de golf", "Scarpe da golf", "골프화", "高爾夫球鞋"),
    "帽子・サンバイザー": _t("Cap / visor", "Kappe / Visier", "Gorra / visera", "Casquette / visière", "Cappello / visiera", "모자·바이저", "帽子・遮陽帽"),
    "レインウェア": _t("Rain gear", "Regenkleidung", "Chubasquero", "Vêtement de pluie", "Antipioggia", "우비", "雨衣"),
    "ラケット": _t("Racket", "Schläger", "Raqueta", "Raquette", "Racchetta", "라켓", "球拍"),
    "テニスボール": _t("Tennis balls", "Tennisbälle", "Pelotas de tenis", "Balles de tennis", "Palline da tennis", "테니스공", "網球"),
    "テニスシューズ": _t("Tennis shoes", "Tennisschuhe", "Zapatillas de tenis", "Chaussures de tennis", "Scarpe da tennis", "테니스화", "網球鞋"),
    "グリップテープ": _t("Grip tape", "Griffband", "Grip", "Grip", "Grip", "그립 테이프", "握把布"),
    "テニスウェア": _t("Tennis wear", "Tenniskleidung", "Ropa de tenis", "Tenue de tennis", "Abbigliamento tennis", "테니스 웨어", "網球服"),
    "リストバンド": _t("Wristband", "Schweißband", "Muñequera", "Bracelet éponge", "Polsino", "손목밴드", "護腕"),
    "スポーツドリンク": _t("Sports drink", "Sportgetränk", "Bebida isotónica", "Boisson sportive", "Bevanda sportiva", "스포츠 음료", "運動飲料"),
    "スキーウェア(上下)": _t("Ski wear", "Skibekleidung", "Ropa de esquí", "Tenue de ski", "Abbigliamento da sci", "스키복(상하)", "滑雪服(上下)"),
    "インナー(上下)": _t("Base layer", "Funktionswäsche", "Capa base", "Sous-couche", "Strato base", "이너(상하)", "內層(上下)"),
    "ネックウォーマー": _t("Neck warmer", "Halswärmer", "Cuellos", "Tour de cou", "Scaldacollo", "넥워머", "頸套"),
    "ゴーグル": _t("Goggles", "Skibrille", "Gafas", "Masque", "Maschera", "고글", "護目鏡"),
    "ニット帽": _t("Beanie", "Mütze", "Gorro", "Bonnet", "Berretto", "니트 모자", "毛帽"),
    "厚手ソックス": _t("Thick socks", "Dicke Socken", "Calcetines gruesos", "Chaussettes épaisses", "Calzini spessi", "두꺼운 양말", "厚襪"),
    "カイロ": _t("Hand warmers", "Handwärmer", "Calentadores de manos", "Chaufferettes", "Scaldamani", "핫팩", "暖暖包"),
    "リップクリーム": _t("Lip balm", "Lippenbalsam", "Bálsamo labial", "Baume à lèvres", "Burrocacao", "립밤", "護唇膏"),
    "現金・IC": _t("Cash / IC card", "Bargeld / Karte", "Efectivo / tarjeta", "Espèces / carte", "Contanti / tessera", "현금·교통카드", "現金・電子票證"),
    "クライミングシューズ": _t("Climbing shoes", "Kletterschuhe", "Pies de gato", "Chaussons d'escalade", "Scarpette da arrampicata", "암벽화", "攀岩鞋"),
    "チョークバッグ": _t("Chalk bag", "Chalkbag", "Bolsa de magnesio", "Sac à magnésie", "Sacca porta-magnesite", "초크백", "粉袋"),
    "チョーク": _t("Chalk", "Chalk", "Magnesio", "Magnésie", "Magnesite", "초크", "止滑粉"),
    "テーピング": _t("Tape", "Tape", "Esparadrapo", "Strapping", "Tape", "테이핑", "肌貼"),
    "動きやすい服": _t("Athletic clothes", "Bequeme Kleidung", "Ropa cómoda", "Vêtements souples", "Abbigliamento comodo", "활동복", "好活動的衣物"),
    "ブラシ": _t("Hold brush", "Griffbürste", "Cepillo de presas", "Brosse", "Spazzola", "홀드 브러시", "岩點刷"),
    "スパイク・シューズ": _t("Cleats / shoes", "Stollenschuhe", "Botas de tacos", "Crampons", "Scarpini", "축구화", "釘鞋"),
    "すね当て": _t("Shin guards", "Schienbeinschoner", "Espinilleras", "Protège-tibias", "Parastinchi", "정강이 보호대", "護脛"),
    "ユニフォーム": _t("Uniform", "Trikot", "Uniforme", "Maillot", "Divisa", "유니폼", "球衣"),
    "ソックス": _t("Socks", "Stutzen", "Medias", "Chaussettes", "Calzettoni", "양말", "球襪"),
    "ヨガマット": _t("Yoga mat", "Yogamatte", "Esterilla de yoga", "Tapis de yoga", "Tappetino yoga", "요가 매트", "瑜伽墊"),
    "ヨガウェア": _t("Yoga wear", "Yogakleidung", "Ropa de yoga", "Tenue de yoga", "Abbigliamento yoga", "요가복", "瑜伽服"),
    "フェイスタオル": _t("Face towel", "Handtuch", "Toalla", "Serviette", "Asciugamano", "페이스 타월", "毛巾"),
    "ヨガブロック": _t("Yoga block", "Yogablock", "Bloque de yoga", "Brique de yoga", "Blocco yoga", "요가 블록", "瑜伽磚"),
    "汗拭きシート": _t("Body wipes", "Erfrischungstücher", "Toallitas corporales", "Lingettes corporelles", "Salviette corpo", "땀 티슈", "濕紙巾"),
    # スポーツ memo
    "__memo__gym_workout": _t("Wear, shoes, and towel basics. Don't forget protein.", "Kleidung, Schuhe und Handtuch. Protein nicht vergessen.", "Ropa, zapatillas y toalla. No olvides la proteína.", "Tenue, chaussures et serviette. N'oubliez pas les protéines.", "Abbigliamento, scarpe e asciugamano. Non dimenticare le proteine.", "옷·신발·수건 기본. 프로틴도 잊지 마세요.", "服裝、鞋子、毛巾基本組。別忘了乳清蛋白。"),
    "__memo__running": _t("Running essentials. Reflectors and a light for night runs.", "Lauf-Essentials. Reflektoren und Licht für Nachtläufe.", "Básicos de running. Reflectantes y luz para correr de noche.", "Essentiels de course. Réflecteurs et lampe pour la nuit.", "Essenziali per la corsa. Riflettenti e luce per la notte.", "러닝 필수품. 야간 러닝용 반사재와 라이트.", "跑步必備。夜跑用反光片與燈。"),
    "__memo__golf": _t("A full round setup. Sun and rain protection too.", "Komplette Runde. Auch Sonnen- und Regenschutz.", "Equipo para una ronda. Protección de sol y lluvia.", "Tenue pour un parcours. Protection soleil et pluie.", "Set per un giro. Anche protezione da sole e pioggia.", "라운드 한 판 세트. 햇볕·비 대비도.", "一整場的裝備。也備妥防曬防雨。"),
    "__memo__tennis": _t("Racket, shoes, balls. Plus sweat management.", "Schläger, Schuhe, Bälle. Plus Schweißmanagement.", "Raqueta, zapatillas, pelotas. Y control del sudor.", "Raquette, chaussures, balles. Et gestion de la transpiration.", "Racchetta, scarpe, palline. E gestione del sudore.", "라켓·신발·공. 땀 관리까지.", "球拍、鞋子、球。加上排汗對策。"),
    "__memo__ski_snowboard": _t("Slope gear. Keep it warm and waterproof.", "Pisten-Ausrüstung. Warm und wasserdicht halten.", "Equipo de pista. Abrigado e impermeable.", "Matériel de piste. Au chaud et imperméable.", "Attrezzatura da pista. Caldo e impermeabile.", "슬로프 장비. 따뜻하고 방수되게.", "雪場裝備。保暖又防水。"),
    "__memo__bouldering": _t("Gym bag basics. Shoes and chalk are key.", "Basics für die Kletterhalle. Schuhe und Chalk sind wichtig.", "Básicos para el rocódromo. Pies de gato y magnesio.", "Basics pour la salle. Chaussons et magnésie essentiels.", "Basics per la palestra. Scarpette e magnesite sono chiave.", "실내 암장 기본. 암벽화와 초크가 핵심.", "岩館基本組。攀岩鞋與止滑粉是重點。"),
    "__memo__soccer_futsal": _t("Practice and match basics. Don't forget shin guards.", "Basics für Training und Spiel. Schienbeinschoner nicht vergessen.", "Básicos de entreno y partido. No olvides las espinilleras.", "Basics entraînement et match. N'oubliez pas les protège-tibias.", "Basics per allenamento e partita. Non dimenticare i parastinchi.", "훈련·경기 기본. 정강이 보호대 잊지 마세요.", "練習與比賽基本組。別忘了護脛。"),
    "__memo__yoga": _t("For the studio. Mat and towel are the basics.", "Fürs Studio. Matte und Handtuch sind Basics.", "Para el estudio. Esterilla y toalla, lo básico.", "Pour le studio. Tapis et serviette, l'essentiel.", "Per lo studio. Tappetino e asciugamano, l'essenziale.", "스튜디오용. 매트와 수건이 기본.", "上課用。瑜伽墊與毛巾是基本。"),

    # ===== 第3カテゴリ（趣味アウトドア）=====
    "釣り": _t("Fishing", "Angeln", "Pesca", "Pêche", "Pesca", "낚시", "釣魚"),
    "ソロキャンプ": _t("Solo Camping", "Solo-Camping", "Camping en solitario", "Camping solo", "Campeggio in solitaria", "솔로 캠핑", "單人露營"),
    "サイクリング": _t("Cycling", "Radfahren", "Ciclismo", "Cyclisme", "Ciclismo", "사이클링", "自行車"),
    "BBQ": _t("BBQ", "Grillen", "Barbacoa", "Barbecue", "Barbecue", "바비큐", "烤肉"),
    "天体観測": _t("Stargazing", "Sternbeobachtung", "Observación de estrellas", "Observation des étoiles", "Osservazione stelle", "천체 관측", "觀星"),
    "写真撮影": _t("Photography", "Fotografie", "Fotografía", "Photographie", "Fotografia", "사진 촬영", "攝影"),
    "🎣 タックル": _t("🎣 Tackle", "🎣 Angelzeug", "🎣 Aparejos", "🎣 Matériel", "🎣 Attrezzatura", "🎣 태클", "🎣 釣具"),
    "🦺 安全・快適": _t("🦺 Safety & comfort", "🦺 Sicherheit & Komfort", "🦺 Seguridad y confort", "🦺 Sécurité et confort", "🦺 Sicurezza e comfort", "🦺 안전·편의", "🦺 安全・舒適"),
    "🍙 飲食・その他": _t("🍙 Food & misc", "🍙 Essen & Sonstiges", "🍙 Comida y otros", "🍙 Nourriture et divers", "🍙 Cibo e varie", "🍙 음식·기타", "🍙 飲食・其他"),
    "⛺ 宿泊": _t("⛺ Shelter & sleep", "⛺ Übernachtung", "⛺ Pernocta", "⛺ Couchage", "⛺ Pernottamento", "⛺ 숙박", "⛺ 住宿"),
    "🔥 焚き火・調理": _t("🔥 Fire & cooking", "🔥 Feuer & Kochen", "🔥 Fuego y cocina", "🔥 Feu et cuisine", "🔥 Fuoco e cucina", "🔥 모닥불·조리", "🔥 生火・烹調"),
    "🔦 その他": _t("🔦 Misc", "🔦 Sonstiges", "🔦 Otros", "🔦 Divers", "🔦 Varie", "🔦 기타", "🔦 其他"),
    "🚴 装備": _t("🚴 Gear", "🚴 Ausrüstung", "🚴 Equipo", "🚴 Équipement", "🚴 Attrezzatura", "🚴 장비", "🚴 裝備"),
    "🔧 メンテ・補給": _t("🔧 Repair & fuel", "🔧 Reparatur & Verpflegung", "🔧 Reparación y avituallamiento", "🔧 Réparation et ravitaillement", "🔧 Riparazione e rifornimento", "🔧 정비·보급", "🔧 維修・補給"),
    "🔥 コンロまわり": _t("🔥 Grill", "🔥 Grill", "🔥 Parrilla", "🔥 Gril", "🔥 Griglia", "🔥 그릴", "🔥 烤爐"),
    "🍖 食器・食材": _t("🍖 Tableware & food", "🍖 Geschirr & Lebensmittel", "🍖 Vajilla y comida", "🍖 Vaisselle et aliments", "🍖 Stoviglie e cibo", "🍖 식기·식재료", "🍖 餐具・食材"),
    "🪑 快適・その他": _t("🪑 Comfort & misc", "🪑 Komfort & Sonstiges", "🪑 Comodidad y otros", "🪑 Confort et divers", "🪑 Comfort e varie", "🪑 편의·기타", "🪑 舒適・其他"),
    "🔭 観測用品": _t("🔭 Observation", "🔭 Beobachtung", "🔭 Observación", "🔭 Observation", "🔭 Osservazione", "🔭 관측 용품", "🔭 觀測用品"),
    "🧥 防寒・快適": _t("🧥 Warmth & comfort", "🧥 Wärme & Komfort", "🧥 Abrigo y confort", "🧥 Chaleur et confort", "🧥 Calore e comfort", "🧥 방한·편의", "🧥 保暖・舒適"),
    "📷 機材": _t("📷 Equipment", "📷 Ausrüstung", "📷 Equipo", "📷 Matériel", "📷 Attrezzatura", "📷 장비", "📷 器材"),
    "💾 サポート": _t("💾 Support", "💾 Zubehör", "💾 Apoyo", "💾 Support", "💾 Supporto", "💾 서포트", "💾 輔助"),
    "竿・リール": _t("Rod & reel", "Rute & Rolle", "Caña y carrete", "Canne et moulinet", "Canna e mulinello", "낚싯대·릴", "釣竿・捲線器"),
    "仕掛け・ルアー": _t("Rigs & lures", "Montagen & Köder", "Aparejos y señuelos", "Montages et leurres", "Montature ed esche", "채비·루어", "釣組・擬餌"),
    "バケツ・網": _t("Bucket & net", "Eimer & Kescher", "Cubo y red", "Seau et épuisette", "Secchio e retino", "양동이·뜰채", "水桶・網子"),
    "ライフジャケット": _t("Life vest", "Schwimmweste", "Chaleco salvavidas", "Gilet de sauvetage", "Giubbotto salvagente", "구명조끼", "救生衣"),
    "帽子・偏光サングラス": _t("Cap & sunglasses", "Kappe & Sonnenbrille", "Gorra y gafas polarizadas", "Casquette et lunettes", "Cappello e occhiali", "모자·편광 선글라스", "帽子・偏光墨鏡"),
    "タオル・手拭き": _t("Towel & wipes", "Handtuch & Tücher", "Toalla y toallitas", "Serviette et lingettes", "Asciugamano e salviette", "수건·물티슈", "毛巾・擦手巾"),
    "軽food": _t("Snacks", "Snacks", "Aperitivos", "En-cas", "Snack", "간식", "點心"),
    "ゴミ袋": _t("Trash bags", "Müllbeutel", "Bolsas de basura", "Sacs poubelle", "Sacchi spazzatura", "쓰레기 봉투", "垃圾袋"),
    "ソロテント": _t("Solo tent", "Solo-Zelt", "Tienda individual", "Tente solo", "Tenda singola", "1인 텐트", "單人帳篷"),
    "チェア": _t("Camp chair", "Campingstuhl", "Silla de camping", "Chaise de camp", "Sedia da campeggio", "캠핑 의자", "露營椅"),
    "シングルバーナー": _t("Single burner", "Einzelkocher", "Hornillo individual", "Réchaud simple", "Fornello singolo", "싱글 버너", "單口爐"),
    "コーヒーセット": _t("Coffee set", "Kaffeeset", "Set de café", "Kit café", "Set caffè", "커피 세트", "咖啡組"),
    "ナイフ": _t("Knife", "Messer", "Cuchillo", "Couteau", "Coltello", "나이프", "刀具"),
    "ヘルメット": _t("Helmet", "Helm", "Casco", "Casque", "Casco", "헬멧", "安全帽"),
    "サングラス": _t("Sunglasses", "Sonnenbrille", "Gafas de sol", "Lunettes de soleil", "Occhiali da sole", "선글라스", "太陽眼鏡"),
    "ボトル": _t("Water bottle", "Trinkflasche", "Bidón", "Bidon", "Borraccia", "물통", "水壺"),
    "予備チューブ": _t("Spare tube", "Ersatzschlauch", "Cámara de repuesto", "Chambre à air de rechange", "Camera d'aria di scorta", "예비 튜브", "備用內胎"),
    "携帯ポンプ": _t("Mini pump", "Minipumpe", "Bomba de mano", "Pompe à main", "Pompa portatile", "휴대용 펌프", "隨身打氣筒"),
    "携帯工具": _t("Multi-tool", "Multitool", "Multiherramienta", "Multi-outil", "Multiutensile", "멀티툴", "多功能工具"),
    "補給食": _t("Energy food", "Energieriegel", "Comida energética", "Ravitaillement", "Cibo energetico", "보급식", "補給食物"),
    "BBQコンロ": _t("BBQ grill", "Grill", "Barbacoa", "Barbecue", "Griglia", "바비큐 그릴", "烤肉爐"),
    "炭": _t("Charcoal", "Grillkohle", "Carbón", "Charbon", "Carbone", "숯", "木炭"),
    "着火剤・トング": _t("Lighter & tongs", "Anzünder & Zange", "Pastillas y pinzas", "Allume-feu et pince", "Accendifuoco e pinze", "착화제·집게", "助燃劑・夾子"),
    "紙皿・カップ": _t("Paper plates & cups", "Pappteller & Becher", "Platos y vasos", "Assiettes et gobelets", "Piatti e bicchieri", "종이접시·컵", "紙盤・紙杯"),
    "調味料": _t("Seasonings", "Gewürze", "Condimentos", "Assaisonnements", "Condimenti", "조미료", "調味料"),
    "虫除け": _t("Bug spray", "Insektenspray", "Repelente", "Anti-moustique", "Repellente", "벌레 퇴치제", "防蟲液"),
    "双眼鏡・望遠鏡": _t("Binoculars / telescope", "Fernglas / Teleskop", "Prismáticos / telescopio", "Jumelles / télescope", "Binocolo / telescopio", "쌍안경·망원경", "雙筒・望遠鏡"),
    "星座早見盤": _t("Star chart", "Sternkarte", "Planisferio", "Carte du ciel", "Mappa stellare", "성좌판", "星座盤"),
    "赤色ライト": _t("Red light", "Rotlicht", "Luz roja", "Lampe rouge", "Luce rossa", "적색 라이트", "紅光燈"),
    "ブランケット": _t("Blanket", "Decke", "Manta", "Couverture", "Coperta", "담요", "毯子"),
    "温かい飲み物": _t("Hot drink", "Heißgetränk", "Bebida caliente", "Boisson chaude", "Bevanda calda", "따뜻한 음료", "熱飲"),
    "カメラ本体": _t("Camera body", "Kameragehäuse", "Cuerpo de cámara", "Boîtier", "Corpo macchina", "카메라 본체", "相機機身"),
    "レンズ": _t("Lens", "Objektiv", "Objetivo", "Objectif", "Obiettivo", "렌즈", "鏡頭"),
    "三脚": _t("Tripod", "Stativ", "Trípode", "Trépied", "Treppiede", "삼각대", "三腳架"),
    "予備バッテリー": _t("Spare battery", "Ersatzakku", "Batería de repuesto", "Batterie de rechange", "Batteria di scorta", "예비 배터리", "備用電池"),
    "SDカード": _t("SD card", "SD-Karte", "Tarjeta SD", "Carte SD", "Scheda SD", "SD 카드", "SD 卡"),
    "レンズ拭き": _t("Lens cloth", "Objektivtuch", "Paño de lente", "Chiffon objectif", "Panno per obiettivo", "렌즈 크리너", "拭鏡布"),
    "ブロワー": _t("Air blower", "Blasebalg", "Soplador", "Soufflette", "Soffietto", "블로어", "吹球"),
    "__memo__fishing": _t("Pier and sea fishing basics. Always wear a life vest.", "Basics fürs Angeln an Mole und Meer. Immer Schwimmweste tragen.", "Básicos de pesca en muelle y mar. Lleva siempre chaleco.", "Basics de pêche en jetée et en mer. Toujours porter un gilet.", "Basics per la pesca da molo e mare. Indossa sempre il giubbotto.", "방파제·바다 낚시 기본. 구명조끼는 필수.", "堤防與海釣基本組。務必穿救生衣。"),
    "__memo__camp_solo": _t("Lightweight solo gear. Fire and coffee for me-time.", "Leichte Solo-Ausrüstung. Feuer und Kaffee für Me-Time.", "Equipo ligero en solitario. Fuego y café para ti.", "Matériel solo léger. Feu et café pour un moment à soi.", "Attrezzatura solo leggera. Fuoco e caffè per te.", "가벼운 솔로 장비. 모닥불과 커피로 나만의 시간.", "輕量單人裝備。生火煮咖啡享受獨處。"),
    "__memo__cycling": _t("Long-ride kit. Puncture repair and fuel are key.", "Set für lange Touren. Reifenpanne und Verpflegung wichtig.", "Kit para rutas largas. Reparación de pinchazos y avituallamiento.", "Kit longue distance. Réparation de crevaison et ravitaillement.", "Kit per lunghe pedalate. Riparazione forature e rifornimento.", "롱라이드 세트. 펑크 수리와 보급이 핵심.", "長途騎乘組。補胎與補給是重點。"),
    "__memo__bbq": _t("Day BBQ by the river. Charcoal and a lighter are essential.", "Tages-Grillen am Fluss. Kohle und Anzünder unverzichtbar.", "Barbacoa junto al río. Carbón y encendedor imprescindibles.", "Barbecue au bord de la rivière. Charbon et allume-feu essentiels.", "Barbecue al fiume. Carbone e accendino essenziali.", "강가 데이 바비큐. 숯과 착화제 필수.", "河邊烤肉一日遊。木炭與助燃劑必備。"),
    "__memo__stargazing": _t("For the night sky. Warm layers and a red light help.", "Für den Nachthimmel. Warme Kleidung und Rotlicht helfen.", "Para el cielo nocturno. Abrigo y luz roja ayudan.", "Pour le ciel nocturne. Vêtements chauds et lampe rouge.", "Per il cielo notturno. Vestiti caldi e luce rossa aiutano.", "밤하늘을 위해. 방한복과 적색 라이트가 도움.", "為了觀賞夜空。保暖衣物與紅光燈很有幫助。"),
    "__memo__photography": _t("For a photo trip. Spare batteries and lens cloth.", "Für einen Fototrip. Ersatzakkus und Objektivtuch.", "Para una salida fotográfica. Baterías extra y paño de lente.", "Pour une sortie photo. Batteries de rechange et chiffon.", "Per un'uscita fotografica. Batterie di scorta e panno.", "사진 촬영 여행에. 예비 배터리와 렌즈 크리너.", "攝影出遊用。備用電池與拭鏡布。"),

    # ===== 第4カテゴリ（インドア・季節ライフイベント）=====
    "ライブ・コンサート": _t("Live Concert", "Konzert", "Concierto", "Concert", "Concerto", "라이브·콘서트", "演唱會"),
    "映画館": _t("Cinema", "Kino", "Cine", "Cinéma", "Cinema", "영화관", "電影院"),
    "ボードゲーム会": _t("Board Game Night", "Brettspielabend", "Noche de juegos de mesa", "Soirée jeux de société", "Serata giochi da tavolo", "보드게임 모임", "桌遊聚會"),
    "海水浴": _t("Beach", "Strandtag", "Playa", "Plage", "Spiaggia", "해수욕", "海水浴"),
    "入院": _t("Hospital Stay", "Krankenhausaufenthalt", "Hospitalización", "Hospitalisation", "Ricovero", "입원", "住院"),
    "引っ越し": _t("Moving Day", "Umzug", "Mudanza", "Déménagement", "Trasloco", "이사", "搬家"),
    "結婚式参列": _t("Wedding Guest", "Hochzeitsgast", "Boda (invitado)", "Invité à un mariage", "Ospite a un matrimonio", "결혼식 참석", "參加婚禮"),
    "資格試験": _t("Exam Day", "Prüfungstag", "Día de examen", "Jour d'examen", "Giorno d'esame", "자격시험", "考試"),
    "🎫 必需品": _t("🎫 Essentials", "🎫 Grundlegendes", "🎫 Imprescindibles", "🎫 Indispensables", "🎫 Essenziali", "🎫 필수품", "🎫 必需品"),
    "🎬 持ち物": _t("🎬 Items", "🎬 Sachen", "🎬 Objetos", "🎬 Affaires", "🎬 Oggetti", "🎬 소지품", "🎬 隨身物"),
    "🎲 ゲーム": _t("🎲 Games", "🎲 Spiele", "🎲 Juegos", "🎲 Jeux", "🎲 Giochi", "🎲 게임", "🎲 遊戲"),
    "🍿 差し入れ": _t("🍿 Snacks", "🍿 Snacks", "🍿 Aperitivos", "🍿 En-cas", "🍿 Snack", "🍿 간식", "🍿 點心"),
    "🏖 ビーチ用品": _t("🏖 Beach items", "🏖 Strandsachen", "🏖 Artículos de playa", "🏖 Articles de plage", "🏖 Articoli da spiaggia", "🏖 비치 용품", "🏖 海灘用品"),
    "☀️ 対策・ケア": _t("☀️ Protection", "☀️ Schutz", "☀️ Protección", "☀️ Protection", "☀️ Protezione", "☀️ 대비·케어", "☀️ 防護・保養"),
    "🧾 手続き・必需品": _t("🧾 Admin & essentials", "🧾 Formalitäten & Basics", "🧾 Trámites y básicos", "🧾 Démarches et essentiels", "🧾 Pratiche ed essenziali", "🧾 수속·필수품", "🧾 手續・必需品"),
    "🧺 身の回り": _t("🧺 Personal care", "🧺 Persönliches", "🧺 Aseo personal", "🧺 Affaires personnelles", "🧺 Cura personale", "🧺 개인 용품", "🧺 隨身用品"),
    "📱 快適グッズ": _t("📱 Comfort", "📱 Komfort", "📱 Comodidad", "📱 Confort", "📱 Comfort", "📱 편의용품", "📱 舒適小物"),
    "🔧 作業道具": _t("🔧 Tools", "🔧 Werkzeug", "🔧 Herramientas", "🔧 Outils", "🔧 Attrezzi", "🔧 작업 도구", "🔧 工具"),
    "📦 すぐ使う物": _t("📦 First-night items", "📦 Sofort nötig", "📦 De uso inmediato", "📦 Première nuit", "📦 Prima notte", "📦 바로 쓸 물건", "📦 立即要用的"),
    "🧾 手続き": _t("🧾 Paperwork", "🧾 Formalitäten", "🧾 Trámites", "🧾 Démarches", "🧾 Pratiche", "🧾 수속", "🧾 手續"),
    "🎁 マナー品": _t("🎁 Etiquette items", "🎁 Etikette", "🎁 Protocolo", "🎁 Étiquette", "🎁 Galateo", "🎁 예절 용품", "🎁 禮儀用品"),
    "👗 身だしなみ": _t("👗 Grooming", "👗 Pflege", "👗 Arreglo personal", "👗 Apprêt", "👗 Cura personale", "👗 몸단장", "👗 儀容"),
    "📝 受験必需品": _t("📝 Exam essentials", "📝 Prüfungsbedarf", "📝 Imprescindibles de examen", "📝 Indispensables d'examen", "📝 Essenziali d'esame", "📝 시험 필수품", "📝 應考必需品"),
    "🧥 コンディション": _t("🧥 Condition", "🧥 Verfassung", "🧥 A punto", "🧥 En forme", "🧥 Condizione", "🧥 컨디션", "🧥 狀態調整"),
    "チケット": _t("Ticket", "Ticket", "Entrada", "Billet", "Biglietto", "티켓", "門票"),
    "ペンライト": _t("Glow stick", "Leuchtstab", "Barra luminosa", "Bâton lumineux", "Bastoncino luminoso", "펜라이트", "螢光棒"),
    "身分証": _t("ID", "Ausweis", "DNI", "Pièce d'identité", "Documento", "신분증", "證件"),
    "現金・交通IC": _t("Cash / transit card", "Bargeld / Fahrkarte", "Efectivo / tarjeta de transporte", "Espèces / carte de transport", "Contanti / tessera trasporti", "현금·교통카드", "現金・交通卡"),
    "うちわ・応援グッズ": _t("Fan goods", "Fanartikel", "Artículos de fan", "Objets de fan", "Gadget da fan", "응원 굿즈", "應援小物"),
    "チケット・会員証": _t("Ticket / membership", "Ticket / Mitgliedskarte", "Entrada / socio", "Billet / carte membre", "Biglietto / tessera", "티켓·회원증", "門票・會員卡"),
    "のど飴": _t("Throat candy", "Halsbonbons", "Caramelos de garganta", "Pastilles pour la gorge", "Caramelle per la gola", "목 캔디", "喉糖"),
    "ハンカチ": _t("Handkerchief", "Taschentuch", "Pañuelo", "Mouchoir", "Fazzoletto", "손수건", "手帕"),
    "ボードゲーム": _t("Board games", "Brettspiele", "Juegos de mesa", "Jeux de société", "Giochi da tavolo", "보드게임", "桌遊"),
    "カードゲーム": _t("Card games", "Kartenspiele", "Juegos de cartas", "Jeux de cartes", "Giochi di carte", "카드게임", "紙牌遊戲"),
    "得点メモ・ペン": _t("Scorepad & pen", "Zettel & Stift", "Marcador y bolígrafo", "Bloc de score et stylo", "Segnapunti e penna", "점수 메모·펜", "計分紙・筆"),
    "タイマー": _t("Timer", "Timer", "Temporizador", "Minuteur", "Timer", "타이머", "計時器"),
    "お菓子": _t("Snacks", "Süßigkeiten", "Aperitivos", "Snacks", "Snack", "간식", "零食"),
    "水着": _t("Swimsuit", "Badeanzug", "Bañador", "Maillot de bain", "Costume", "수영복", "泳衣"),
    "ビーチタオル": _t("Beach towel", "Strandtuch", "Toalla de playa", "Serviette de plage", "Telo mare", "비치 타월", "海灘巾"),
    "サンダル": _t("Sandals", "Sandalen", "Sandalias", "Sandales", "Sandali", "샌들", "涼鞋"),
    "浮き輪・レジャーシート": _t("Float & sheet", "Schwimmreifen & Decke", "Flotador y esterilla", "Bouée et tapis", "Ciambella e telo", "튜브·돗자리", "泳圈・野餐墊"),
    "サングラス・帽子": _t("Sunglasses & hat", "Sonnenbrille & Hut", "Gafas y sombrero", "Lunettes et chapeau", "Occhiali e cappello", "선글라스·모자", "墨鏡・帽子"),
    "防水ケース": _t("Waterproof case", "Wasserdichte Hülle", "Funda impermeable", "Étui étanche", "Custodia impermeabile", "방수 케이스", "防水套"),
    "保険証・診察券": _t("Insurance & patient card", "Versichertenkarte & Patientenkarte", "Tarjeta sanitaria y de paciente", "Carte d'assurance et de patient", "Tessera sanitaria e paziente", "보험증·진료카드", "健保卡・就診卡"),
    "印鑑": _t("Personal seal", "Stempel", "Sello personal", "Cachet personnel", "Timbro personale", "인감", "印章"),
    "パジャマ・下着": _t("Pajamas & underwear", "Schlafanzug & Unterwäsche", "Pijama y ropa interior", "Pyjama et sous-vêtements", "Pigiama e intimo", "잠옷·속옷", "睡衣・內衣褲"),
    "スリッパ": _t("Slippers", "Hausschuhe", "Zapatillas", "Chaussons", "Pantofole", "슬리퍼", "拖鞋"),
    "スマホ・充電器": _t("Phone & charger", "Handy & Ladegerät", "Móvil y cargador", "Téléphone et chargeur", "Telefono e caricatore", "스마트폰·충전기", "手機・充電器"),
    "本・雑誌": _t("Books / magazines", "Bücher / Zeitschriften", "Libros / revistas", "Livres / magazines", "Libri / riviste", "책·잡지", "書・雜誌"),
    "ティッシュ・ウェット": _t("Tissues & wipes", "Taschentücher & Feuchttücher", "Pañuelos y toallitas", "Mouchoirs et lingettes", "Fazzoletti e salviette", "티슈·물티슈", "面紙・濕紙巾"),
    "カッター・はさみ": _t("Utility knife & scissors", "Cutter & Schere", "Cúter y tijeras", "Cutter et ciseaux", "Taglierino e forbici", "커터·가위", "美工刀・剪刀"),
    "ガムテープ": _t("Packing tape", "Klebeband", "Cinta de embalar", "Ruban adhésif", "Nastro da imballaggio", "박스 테이프", "封箱膠帶"),
    "マジック・ラベル": _t("Markers & labels", "Marker & Etiketten", "Rotuladores y etiquetas", "Marqueurs et étiquettes", "Pennarelli ed etichette", "매직·라벨", "麥克筆・標籤"),
    "トイレットペーパー": _t("Toilet paper", "Toilettenpapier", "Papel higiénico", "Papier toilette", "Carta igienica", "화장지", "衛生紙"),
    "契約書類": _t("Contract documents", "Vertragsunterlagen", "Documentos del contrato", "Documents du contrat", "Documenti del contratto", "계약 서류", "合約文件"),
    "ご祝儀袋": _t("Gift money envelope", "Geldgeschenk-Umschlag", "Sobre para dinero", "Enveloppe cadeau", "Busta regalo", "축의금 봉투", "禮金袋"),
    "袱紗": _t("Gift envelope wrap", "Umschlag-Tuch", "Funda del sobre", "Étui à enveloppe", "Custodia per busta", "후쿠사(봉투 보자기)", "禮金袋巾"),
    "招待状": _t("Invitation", "Einladung", "Invitación", "Invitation", "Invito", "초대장", "邀請函"),
    "新札": _t("New bills", "Neue Geldscheine", "Billetes nuevos", "Billets neufs", "Banconote nuove", "새 지폐", "新鈔"),
    "フォーマル靴": _t("Formal shoes", "Anzugschuhe", "Zapatos de vestir", "Chaussures habillées", "Scarpe eleganti", "정장 구두", "正式皮鞋"),
    "予備ストッキング": _t("Spare stockings", "Ersatzstrumpfhose", "Medias de repuesto", "Collants de rechange", "Collant di riserva", "예비 스타킹", "備用絲襪"),
    "メイク直し": _t("Makeup touch-up", "Make-up zum Nachbessern", "Retoque de maquillaje", "Retouche maquillage", "Ritocco trucco", "메이크업 수정 도구", "補妝用品"),
    "受験票": _t("Admission ticket", "Prüfungsausweis", "Hoja de admisión", "Convocation", "Foglio d'ammissione", "수험표", "准考證"),
    "筆記用具": _t("Writing tools", "Schreibzeug", "Material de escritura", "Matériel d'écriture", "Materiale per scrivere", "필기구", "文具"),
    "腕時計": _t("Watch", "Armbanduhr", "Reloj", "Montre", "Orologio", "손목시계", "手錶"),
    "軽food・チョコ": _t("Snack / chocolate", "Snack / Schokolade", "Aperitivo / chocolate", "En-cas / chocolat", "Snack / cioccolato", "간식·초콜릿", "點心・巧克力"),
    "参考書・要点メモ": _t("Notes", "Lernunterlagen", "Apuntes", "Fiches de révision", "Appunti", "참고서·요점 노트", "參考書・重點筆記"),
    "__memo__live_concert": _t("Show-day prep. Ticket and glow stick are must-haves.", "Vorbereitung für den Konzerttag. Ticket und Leuchtstab sind Pflicht.", "Preparación del día del concierto. Entrada y barra luminosa imprescindibles.", "Préparation du jour du concert. Billet et bâton lumineux indispensables.", "Preparazione per il concerto. Biglietto e bastoncino luminoso indispensabili.", "공연 당일 준비. 티켓과 펜라이트는 필수.", "演唱會當天準備。門票與螢光棒必備。"),
    "__memo__cinema": _t("Comfy movie time. A layer and throat candy help.", "Gemütliche Kinozeit. Eine Jacke und Halsbonbons helfen.", "Cine cómodo. Una capa y caramelos de garganta ayudan.", "Séance ciné confort. Une couche et des pastilles aident.", "Cinema comodo. Uno strato e caramelle per la gola aiutano.", "편안한 영화 관람. 겉옷과 목 캔디가 도움.", "舒適看電影。外搭與喉糖很有用。"),
    "__memo__boardgame": _t("A bring-your-own night. Games and snacks!", "Ein Spieleabend zum Mitbringen. Spiele und Snacks!", "Noche de traer lo tuyo. ¡Juegos y aperitivos!", "Une soirée où chacun apporte. Jeux et en-cas !", "Una serata bring-your-own. Giochi e snack!", "각자 가져오는 모임. 게임과 간식!", "自帶同樂之夜。遊戲與點心！"),
    "__memo__beach": _t("Enjoy the sea. Sun care and a change of clothes.", "Genieße das Meer. Sonnenschutz und Wechselkleidung.", "Disfruta del mar. Protección solar y muda de ropa.", "Profitez de la mer. Protection solaire et rechange.", "Goditi il mare. Protezione solare e cambio d'abiti.", "바다를 즐기세요. 자외선 케어와 갈아입을 옷.", "享受大海。防曬與換洗衣物。"),
    "__memo__hospital_stay": _t("Admission prep. Clothes, toiletries, and something to pass time.", "Vorbereitung fürs Krankenhaus. Kleidung, Pflege und Zeitvertreib.", "Preparación del ingreso. Ropa, aseo y algo para pasar el rato.", "Préparation de l'admission. Vêtements, toilette et de quoi passer le temps.", "Preparazione al ricovero. Abiti, igiene e passatempi.", "입원 준비. 옷·세면·소일거리.", "住院準備。衣物、盥洗、打發時間的東西。"),
    "__memo__moving": _t("Moving day. Keep tools and first-night items handy.", "Umzugstag. Werkzeug und Dinge für die erste Nacht griffbereit.", "Día de mudanza. Ten a mano herramientas y lo de la primera noche.", "Jour du déménagement. Gardez outils et affaires à portée.", "Giorno del trasloco. Tieni a portata attrezzi e cose per la prima notte.", "이사 당일. 공구와 첫날 필요품을 손닿게.", "搬家當天。工具與第一晚用品放手邊。"),
    "__memo__wedding_guest": _t("Wedding guest prep. Don't forget the gift envelope.", "Vorbereitung als Hochzeitsgast. Geldgeschenk nicht vergessen.", "Preparación como invitado. No olvides el sobre del regalo.", "Préparation d'invité. N'oubliez pas l'enveloppe cadeau.", "Preparazione da ospite. Non dimenticare la busta regalo.", "결혼식 하객 준비. 축의금 봉투를 잊지 마세요.", "婚禮賓客準備。別忘了禮金袋。"),
    "__memo__exam": _t("Exam day. Admission ticket, a watch, and layers.", "Prüfungstag. Prüfungsausweis, Uhr und warme Schichten.", "Día de examen. Hoja de admisión, reloj y capas.", "Jour d'examen. Convocation, montre et vêtements en couches.", "Giorno d'esame. Foglio d'ammissione, orologio e strati.", "시험 당일. 수험표·시계·겉옷.", "考試當天。准考證、手錶與保暖層。"),
}
